const axios = require('axios');

function extractSection(prompt, label) {
  const regex = new RegExp(`${label.replace(/[-/\\^$*+?.()|[\]{}]/g, '\\$&')}([\s\S]*?)(?=\n\n[A-Z]|$)`, 'i');
  const match = prompt.match(regex);
  return match ? match[1].trim() : '';
}

function fallbackAnswer(prompt) {
  const context = extractSection(prompt, 'Internal disease database context:');
  const evidence = extractSection(prompt, 'Trusted medical evidence:');
  const userText = extractSection(prompt, 'User message:');

  const conditionsMatch = context.match(/Likely conditions:\s*(.*)/i);
  const redFlagsMatch = context.match(/Red flags:\s*(.*)/i);
  const conditions = conditionsMatch ? conditionsMatch[1] : 'a set of possible conditions';
  const redFlags = redFlagsMatch ? redFlagsMatch[1] : 'serious symptoms requiring evaluation';

  return `Based on your message, I am using the internal medical summary and trusted evidence to provide a careful response. The most likely possibilities include ${conditions}. Clinical reasoning: I am prioritizing symptoms and red flags, and I am looking for the most likely causes rather than making a definitive diagnosis. If you experience ${redFlags}, seek urgent medical evaluation. This response is generated by the backend when the AI endpoint is not configured.`;
}

async function callAILogic(prompt) {
  const endpoint = process.env.LOCAL_AI_ENDPOINT;
  if (endpoint) {
    try {
      const response = await axios.post(endpoint, { prompt }, { headers: { 'Content-Type': 'application/json' }, timeout: 20000 });
      if (response.data?.completion) return response.data.completion;
      if (response.data?.answer) return response.data.answer;
      return typeof response.data === 'string' ? response.data : fallbackAnswer(prompt);
    } catch (err) {
      console.error('AI endpoint request failed:', err.message || err);
      return fallbackAnswer(prompt);
    }
  }
  return fallbackAnswer(prompt);
}

module.exports = { callAILogic };
